import 'package:flutter/material.dart';
import 'package:sizer/sizer.dart';

final List<String> COURSES = [
  //DEFAULT MESSAGE
  "Select a course",
  //MATH COURSES
  "Intensified Algebra 1",
  "Algebra 1/Algebraic Concepts",
  "Geometry in Application",
  "Algebra 2/Advanced Algebraic Concepts",
  "Precalculus",
  "Calculus",
  "Bridge to College Mathematics",
  "Statistics",
  "AP Calculus AB",
  "AP Calculus BC",
  "AP Statistics",
  //ENGLISH COURSES
  "Pre-AP English 1",
  "Pre-AP English 2",
  "English 3",
  "English 4",
  "EvCC English 4",
  "AP Seminar",
  "AP Research",
  "AP English Language & Composition",
  "AP English Literature & Composition",
  "UW English Composition: General",
  "UW English Composition: Literary",
  "UW English Composition: Humanities",
  "Creative Writing",
  "Myth and Legend",
  //SCIENCE COURSES
  "Biology in the Environment",
  "Physics in the Universe",
  "Chemistry in Earth Systems",
  "AP Environmental Sciences",
  "AP Physics 1",
  "AP Physics 2",
  "AP Biology",
  "AP Chemistry",
  "Anatomy & Physiology",
  "Astronomy & Aerospace Engineering",
  "Biotechnology",
  "Engineer Your World",
  "Robotics Technology",
  "Sustainable Agriculture",
  "Science Lab Assistant",
  //HISTORY/SOCIAL STUDIES
  "World History",
  "US History",
  "Washington History",
  "AP Human Geography",
  "AP World History (Modern)",
  "AP US History",
  "AP US Government & Politics",
  "Ethnic Studies & Civics",
  "Civics",
  "Contemporary Global Issues",
  "Philosophy",
  "Sociology",
  "Introduction to Law",
  "Psychology",
  //PHYSICAL EDUCATION
  "Physical Education",
  "Cardio & Core Training",
  "Walking",
  "Yoga Core Training",
  "Lifetime Sports",
  "Sports Performance",
  "Advanced Team Sports",
  "Introduction to Weight Training",
  "Weight Training",
  //LANGUAGES
  "Spanish 1",
  "Spanish 2",
  "Spanish 3",
  "Spanish 4",
  "AP Spanish Language & Culture",
  "AP Spanish Literature & Culture",
  "Spanish for Heritage Speakers 1",
  "Spanish for Heritage Speakers 2",
  "Spanish through Film and Current Issues",
  "French 1",
  "French 2",
  "French 3",
  "French 4",
  "AP French Language & Culture",
  "Chinese 1",
  "Chinese 2",
  "Chinese 3",
  "Chinese 4",
  "AP Chinese Language % Culture",
  "German 1",
  "German 2",
  "German 3",
  "German 4",
  "AP German Language & Culture",
  //CTE
  "Accounting",
  "Business Law",
  "Economics",
  "AP Macroeconomics",
  "AP Microeconomics",
  "AP Psychology",
  "Foundations of Business & Marketing",
  "Social Media Marketing",
  "Entrepreneurship",
  "Business Operations (School Store)",
  "Publications",
  "Computer Applications",
  "AP Computer Science A",
  "AP Computer Science Principles",
  "Cybersecurity & Networking",
  "Computer Programming through Graphics & Animation",
  "Family Health",
  "Child Development",
  "Independent Living",
  "Nutrition & Food Preparation",
  "Nutrition & Wellness",
  "Introduction to Education"
      "Intro to Health Science Careers",
  "Medical Terminology",
  "Sports Medicine",
  "Digital Photography",
  "Introduction to Graphic Design",
  "Graphic Design",
  "Worksite Learning",
  //ARTS
  //Visual
  "Introduction to Art",
  "Ceramics",
  "Cartooning",
  "Drawing & Painting",
  "Sculpture",
  "AP 2-D Art & Design",
  "AP 3-D Art & Design",
  "AP Drawing"
      //Theater
      "Drama",
  "Drama Improvisation",
  "Technical Theater",
  //Music
  "Concert Choir",
  "Symphonic Choir",
  "Treble Choir",
  "Percussion Ensemble"
      "Concert Orchestra",
  "Symphonic Orchestra",
  "Chamber Orchestra",
  "Concert Band",
  "Symphonic Band",
  "Wind Ensemble",
  "Honors Wind Ensemble",
  //OTHER
  "College & Career Readiness Seminar",
  "Teacher or Office Assistant",
  "AVID",
  "Naval Science",
  "Sno-Isle Tech",
  "Running Start"
];

//Staff in alphabetical order
final List<String> STAFF = [
  "Select a teacher",
  "N/A"
      "Katherine Akesson",
  "Rebeca Ambriz de Olivera",
  "Monica Andersen",
  "Nicholas Andersen",
  "Margaret Armstrong",
  "Judy-Gail Baker",
  "Matthew Barry",
  "Travis Birse",
  "Steve Black"
      "Brenda Black",
  "Emily Borden",
  "Allegra Bozorth",
  "Alan Briggs",
  "Alina Bryenton",
  "Elizabeth Burns",
  "Eric Bush",
  "Alexander Chopyak",
  "Robert Crosby",
  "Marisa Cundy",
  "Keelin Davis",
  "Scott Dyer",
  "Deborah Faber",
  "Patricia Faber",
  "Patricia Fankhauser",
  "Bintou Fisiru",
  "Patricia Frank",
  "Todd Freeman",
  "Megan Friedenson",
  "Andrea Gackle",
  "Jason Gadek",
  "Brandon Gallaher",
  "Daniel Geary",
  "Keith Gerhard",
  "Rose Gifford",
  "Diane Gorman",
  "Kathi Guffey",
  "Doug Hall",
  "Stacey Hall",
  "David Heaton-Bush",
  "Johnny Herber",
  "Eric Hruschka",
  "Yiyang Huang",
  "David Hutt",
  "Julie Iverson",
  "Margaret Jensen",
  "Stephen Johnson",
  "Tamera Johnson",
  "Brielle Kemis",
  "Jennifer Kink",
  "Megan Klinich",
  "Orla Korten",
  "Kevin Kukla",
  "Sam Lessard",
  "Brian Lim",
  "Chiu-Hsin Lin",
  "Heidi Little",
  "Michael Lundquist",
  "Natalie Macknight",
  "Brian Marshall",
  "Fady Massoud",
  "Torri McEntire",
  "Dan Mills",
  "Kyle Mitchell",
  "Jessica Montalvo-Lopez",
  "Dan Montzingo",
  "Laura Nelson",
  "Cynthia Nkeze",
  "Wendy Organ",
  "Kim Osada",
  "Kyle Peacocke",
  "Kaye Peterson",
  "Kyle Pihl",
  "Greg Poe",
  "Sinead Pollom",
  "Garett Pope",
  "Stephanie Powell",
  "Ahnya Redman",
  "Maria Reiman",
  "Joseph Rue",
  "Jeana Schafte",
  "Craig Schell",
  "Troy Schwenke",
  "Kathryn Senouillet",
  "Bridget Shee-Anderson",
  "Ryan Simmons",
  "Melissa Sivertsen"
      "Kaja Smith",
  "Pamela Smith",
  "Rose Smith",
  "Daniel Soler",
  "Mike Taggart",
  "Ivette Thompson",
  "Kathleen Thomson",
  "Justin Tobin",
  "Lee Anne Tobin",
  "Rachel Vaught",
  "Joel Vincent",
  "Susan Walker",
  "Christopher Walters",
  "Melanie West"
      "Stephen Wood",
  "Breanna Youngberg"
];

final ButtonStyle NAVBUTTON = ButtonStyle(
    backgroundColor: MaterialStateProperty.all(Color.fromARGB(255, 0, 0, 0)),
    shadowColor: MaterialStateProperty.all(Color.fromARGB(255, 2, 116, 88)),
    textStyle: MaterialStateProperty.all(
        TextStyle(color: Color.fromARGB(255, 255, 255, 255), fontSize: 12.sp)));

final ButtonStyle DEFAULTBUTTON = ButtonStyle(
    backgroundColor: MaterialStateProperty.all(Color.fromARGB(255, 2, 116, 88)),
    shadowColor: MaterialStateProperty.all(Color.fromARGB(255, 0, 0, 0)),
    textStyle: MaterialStateProperty.all(
        TextStyle(color: Color.fromARGB(255, 255, 255, 255), fontSize: 12.sp)));
final TextStyle HEADERTEXT = TextStyle(
  fontSize: 20.sp,
  color: Colors.black,
  fontWeight: FontWeight.bold,
  fontStyle: FontStyle.italic,
  fontFamily: 'Ubuntu',
);

Map<int, Color> THEMECOLOR = {
  50: Color.fromRGBO(2, 116, 88, .1),
  100: Color.fromRGBO(2, 116, 88, .2),
  200: Color.fromRGBO(2, 116, 88, .3),
  300: Color.fromRGBO(2, 116, 88, .4),
  400: Color.fromRGBO(2, 116, 88, .5),
  500: Color.fromRGBO(2, 116, 88, .6),
  600: Color.fromRGBO(2, 116, 88, .7),
  700: Color.fromRGBO(2, 116, 88, .8),
  800: Color.fromRGBO(2, 116, 88, .9),
  900: Color.fromRGBO(2, 116, 88, 1),
};
